version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: criat20_app
    volumes:
      - ./src:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: criat20_postgres
    environment:
      POSTGRES_DB: criat20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: criat20_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app